@startmindmap
* Data Science
** AI
*** Reasoning, problem solving
**** Probabilistinc Model of the world
*** Knowledge representation
**** IBM Watson 
**** Jeopardy
**** Onthology (Knowledge Graphs)
*** Planning & Decision Making
**** Chess
**** AlphaGo
**** Video Ganme AI
**** Self driving cars
*** ML (Machine Learning)
**** supervised learning 
***** Classification
****** Logistic Regression
******* Support Vector Machines (SVM)
****** Random Forests
****** Desicion Trees
****** Bayesian Networks
****** Genetic Programs
****** Nearest Neighbor 
****** Neural Networks
******* Convolutional Neural Networks
***** Regression
****** Linear Regression, 
****** Polynomial Regression, 
****** Decision Trees, 
****** Random Forests, 
****** Gradient Boosting, 
****** Support Vector Regression (SVR)
****** Neural Networks
****** Bayesian Networks
******* Convolutional Neural Networks
***** Anomaly Detection
**** unsupervised learning 
**** semi supervised learning 
**** reinforcement learning
*** NLP - Natural language processing
**** Chat 
**** Translate
**** Alexa
**** NER - Named Entity Recognition
**** Question Answering
**** Summarization
*** Perception
**** Lidar
**** Camera
**** Microphone
*** Motion and manipulation
**** Robotics
**** Actuators - car break, wheel
**** Boston Dynamics robots
*** Social intelligence
**** Robo therapist
**** Sentiment analsys
**** Vision detection
*** AGI - General intelligence
**** Pie in sky goal

@endmindmap
